"""Render current numerical claims directly from the generated result file."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def render(data):
    rows=data['after']
    table='| Role / city | Eligible | Scored | Matches | Must-haves met among matches | Fastest win | Biggest unlock | Confidence |\n|---|---:|---:|---:|---:|---|---|---|\n'
    for city,r in rows.items():
        table+=f"| {r['role']} / {city} | {r['eligible']} | {r['scored']} | {r['matches']} | {r['must_haves_met']} | {r['fastest_win'] or 'Unavailable'} | {r['biggest_unlock'] or 'Unavailable'} | {r['confidence']} |\n"
    f=rows['Bengaluru'];n=rows['Noida'];top=next(x for x in f['ranked'] if x['skill']==f['fastest_win'])
    findings=f"Bengaluru: {f['matches']} of {f['scored']} scored listings match; {top['skill']} adds {top['unlocked']} at {top['hours']:.2f} course hours. Confidence: {f['confidence']}.\n\nNoida: {n['matches']} of {n['scored']} scored listings match; fastest win {n['fastest_win']}, biggest unlock {n['biggest_unlock']}. Confidence: {n['confidence']}.\n\n"
    readme='''# NextSkill

**Your next skill, counted from local job listings in your city.**

[Try it live](https://nextskill.streamlit.app) - saved snapshots, no key needed.

## Why this matters

Early-career applicants need accessible information connecting learning choices to
local opportunities. [ILO/IHD](https://www.ilo.org/publications/india-employment-report-2024-youth-employment-education-and-skills)
examines youth employment and education; [UNICEF](https://www.unicef.org/india/economic-opportunities-young-people)
describes gaps in job awareness and employment support. These sources motivate the
problem; they do not establish NextSkill's effectiveness. [Research and source scope](research/RESEARCH.md).

## Key findings

'''+findings+table+'''
Figures are generated by `python -m scripts.build_results` and `python -m scripts.render_docs`.
See [current results](reports/final_results.json) and [build evidence](BUILD_LOG.md).

## User test and hand-labelled accuracy

Pending. No independent accuracy or user-outcome claim is made.
The historical [matcher audit](reports/matcher_audit.md): 16 of 20 sampled matches were correct; after filters, the 16 retained matches were all correct; recall not measured.
These developer-written checks are not a held-out evaluation. [Initial API validation](reports/validation_check.md).

## What the numbers mean

- Matches: coverage reaches the selected fraction of detected core requirements;
  the default is 50%. It is not hiring eligibility or a prediction.
- Stated must-haves met: yes / no / none stated for detected skills near explicit
  required wording, independently of market frequency. Counts above concern matches
  with explicit requirements met; none-stated listings do not count as yes.
- Course hours: median duration of up to three relevant videos, not time to mastery.
  A title must name the skill or an alias. Fewer than two full courses triggers a
  labelled fallback to relevant videos of at least 30 minutes.
- Confidence: sensitivity to listing resampling and independent hour variation,
  not accuracy. Low-confidence course estimates are labelled separately.
- Exact among measured skills: exhaustive subsets of up to eight candidates with
  known course hours, under the displayed budget. Not a global optimum.

## How it works

SerpApi Jobs supplies role/city listings. The shared engine deduplicates, filters
experience, detects requirements and alternatives, and compares a profile with the
sample. All missing candidates with saved hours compete for Fastest win; candidates
without hours remain visible. Biggest unlock ignores hours. Job Prep orders revision
and learning from the same listing evidence. The opportunity curve and sensitivity
checks expose limitations rather than predict employment.

## SerpApi usage

[Google Jobs](https://serpapi.com/google-jobs-api) supplies descriptions, links,
posting signals and pagination. [YouTube](https://serpapi.com/youtube-search-api)
supplies relevant full-course and short revision-video results.
[Account API](https://serpapi.com/account-api) reports credits and is nonfatal if
unavailable. Each engine materially supports the described functionality; saved
responses allow reproducible offline use. Requests time out after 75 seconds and
are not retried automatically. Live requests have a per-run budget.

## Questions a judge might ask

**Why not just ask ChatGPT?** NextSkill exposes a reproducible count and its exact
listing/course sources. An LLM with search can also cite evidence; our distinction
is a transparent shared calculation, not an assertion that LLM advice is uncheckable.

**Does a match mean an interview?** No. Coverage omits qualifications outside the
vocabulary, and course duration cannot establish competence. Must-haves are a
separate heuristic, not a full eligibility assessment.

## Limitations and future work

Small, biased snapshots; nearby-city results; imperfect required/preferred parsing;
unknown posting ages and course audio languages; no measured learning outcomes.
Title relevance does not prove course quality or suitability for every technology stack.
Independent labels, real user feedback, broader saved markets and language review
remain necessary. Historical iteration reports are in [the archive](reports/archive/README.md).

## Setup and tests

```sh
git clone https://github.com/Anand-240/NextSkill.git
cd NextSkill
python3 -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt
streamlit run app.py
python -m unittest discover -s tests -q
```

PDF resumes require selectable text; scanned PDFs need pasted text. Live search is
for local use with your own authorized key in `.env`; the public hosted app must
never receive a key. Saved data works without one. `.env` and `cache/` are ignored.

## Data sources and privacy

Job descriptions and video metadata remain their publishers' content. The MIT
license covers our code, not third-party material. Contact data in committed
responses is redacted. Resume text is processed by Python; no resume is sent in
SerpApi queries. Streamlit session/cache memory may retain inputs while running;
do not use the public demo for sensitive resumes. [License](LICENSE).

## Development timeline

The original repository began October 8, following a separate validation run.
[BUILD_LOG.md](BUILD_LOG.md) records the subsequent verified build and API budget.
Git history is preserved; earlier measurements remain labelled as historical.

## AI tools used

OpenAI Codex and Claude Code assisted with implementation, tests, analysis and
documentation. The running app does not call an LLM. Human labels and user feedback
are pending and must never be generated by an assistant.
'''
    demo=f'''# NextSkill local demo (2 minutes 45 seconds)

Run `streamlit run app.py` locally. Keep the public hosted app key-free.
Use saved data for rehearsal. A live recording uses a small explicit budget.

| Time | Show and say |
|---|---|
| 0:00-0:30 | Priya knows HTML, CSS and JavaScript and wants a frontend job in Bengaluru. NextSkill checked local listings through SerpApi. Her profile matches {f['matches']} of {f['scored']} scored listings. {top['skill']} could add {top['unlocked']} more; here are the listings and the free courses behind that estimate. |
| 0:30-1:05 | Open listing evidence, must-have status, course sources and confidence: {f['confidence']}. Video duration is not mastery. |
| 1:05-1:25 | Open Job Prep; explain revision versus learning and the full plan. |
| 1:25-1:50 | Compare saved cities and show sample sizes; explain any low-data warning. |
| 1:50-2:20 | Local live search with budget 3. Show Search Replay, partial results and the credit counter. Do not expose the key. |
| 2:20-2:45 | Coverage is not hiring eligibility. Independent labels and user testing are pending. Every recommendation links to its evidence. |

The video must be under three minutes, show the local app, and open without sign-in.
This file is a script, not evidence that a public video has been submitted.
'''
    report='# Current saved results\n\nGenerated from final_results.json; historical reports are in archive/.\n\n'+findings+table
    return {'README.md':readme,'DEMO.md':demo,'reports/final_report.md':report}

if __name__=='__main__':
    for path,body in render(json.loads((ROOT/'reports/final_results.json').read_text())).items():
        (ROOT/path).write_text(body)
